### ISSUE TITLE
uBO issues

### ISSUE THREAD

**Issue by yokoffing** [iam-py-test/uBlock-combo#1]
`https://github.com/iam-py-test/uBlock-combo/blob/main/list.txt`

I'd like to personally use and possible recommend this combined list (to cut down on my custom lists). Do you know why this won't import into uBlock Origin? `https://raw.githubusercontent.com/iam-py-test/uBlock-combo/main/list.txt`

**Comment by iam-py-test** [comment]
For some reason, GitHub doesn't alert me when someone opens an issue **in one of my repos**, so I end up missing issues like this. (in the future, if it looks like I ignored an entire issue, ping me.)
I suspect this is because this "combo" list tries to `#!include` sublists, but these lists do not exist in this repo, so it just fails.
Not sure why uBo just fails to load entire lists due to bad `#!include` lines, instead of just ignoring them.

**Comment by iam-py-test** [comment]
After much random committing (most of which could have been prevented if I didn't make so many typos), it seems to work.
@yokoffing can you test & confirm that it works?

**Comment by yokoffing** [comment]
> For some reason, GitHub doesn't alert me when someone opens an issue in one of my repos, so I end up missing issues like this.

@iam-py-test Yes, I have at least one repo that does that as well. I haven't devoted the time to figure out what Github setting is causing this.

> can you test & confirm that it works?

Yes, it is working now! Thank you!

**Comment by iam-py-test** [comment]
Thank you for reporting this. I wasn't aware people used this list (or tried to use it).

**Comment by yokoffing** [comment]
I came across it randomly one day. It’s nice to have three lists I always use in one combined list (with the anti-typo list as a bonus).
